# ansible_file
---
- name: Install homarr
  hosts: all
  become: true
  tasks:

    - name: Copy compose file
      ansible.builtin.copy:
        src: docker-compose.yaml
        dest: /home/kyo/
        owner: kyo
        group: kyo
        mode: a+rwx
      when: ansible_distribution_major_version == "24"

    - name: Run the compose file
      community.docker.docker_compose_v2:
        project_src: /home/kyo
      when: ansible_distribution_major_version == "24"

    - name: Copy compose file
      ansible.builtin.copy:
        src: docker-compose.yaml
        dest: /home/kona/
        owner: kona
        group: kona
        mode: a+rwx
      when: ansible_distribution_major_version == "22"

    - name: Run the compose file
      community.docker.docker_compose:
        project_src: /home/kona
      when: ansible_distribution_major_version == "22"
